### PR TITLE
2x3 solar panels

### LINKED ISSUE #618: [Feature Request] Better solar panels
The solar panels that are in the mod seem a bit boring. it would be cool if we could have bigger solar panels.

you could add expandable solar panels with solar trackers like this.

image

### PR DESCRIPTION
**Pull request by Baughn**
Resolves #618, #294.

Things that need doing:

- [x] Add flat 2x3 panels.
- [x] Add rotating 2x3 panels.
- [x] Fix cable connection points being slightly off.
- [x] Fix the ghost block bounding boxes being wrong.
- [x] Add 2D icons.
- [x] Adjust the panel model so it isn't floating in the air.
- [x] Recipe for small to large rotating panels.

---
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/634)

### CODE REVIEW

**Comment by AMIDIBOSS** [comment]
I may help you with 2D textures

**Comment by AMIDIBOSS** [comment]
How the cable connections are "slightly off"?

**Comment by Baughn** [comment]
Cable connections are in the center of the block, so to keep them on the 2m side they'd need to be off-center in the panel. I rotated them to be in the middle of the long side instead, but didn't get the positioning perfect. It's easy to fix.

If you want to help, adding 2D icons would definitely be useful. ^_^

**Comment by Baughn** [comment]
I'm using blocks of steel/aluminum in the recipe, by the way...

Those don't exist in all modpacks. Hmm, perhaps alloy blocks would be a good alternative?

**Comment by AMIDIBOSS** [comment]
So...
Make 2D textures for panel and texture for alloy block.
I'll give that... well... Tomorrow may be good?
Today I'm too busy on Project WILDFOREST. It's gotta be great!
and Adk (Our texture artist) is lost...

**Comment by Baughn** [comment]
@AMIDIBOSS I've found some icons, don't worry about it.

The Noun Project is pretty awesome, by the way~~

**Review by AMIDIBOSS — APPROVED** [review]

**Comment by HoodedCr0w** [comment]
Got any pic's?

**Comment by Baughn** [comment]
Rotating panels

You'll note that, unlike the 1x1 panels, that 2x3 panels only rotate to max angles of (-30°, +30°). This is made up for by slightly higher base power output (from fancier hardware, I'm sure); the cost is in-between 6 and 8 panels for 8 panels' output, depending on what you're short of. The intent is to incentivise using them for large solar farms, as they take the same tick time as the small panels for vastly higher output.

The placement rotation is also fixed. That's a compromise I had to make between the model and the sun's orientation. The 2x3 flat panels can be placed at any rotation, of course.

**Comment by AMIDIBOSS** [comment]
Looks awesome

**Comment by HoodedCr0w** [comment]
:3

**Comment by Baughn** [comment]
@cm0x4D Do you have time to look at this?

If not, then I think I can merge. There's nothing particularly sensitive in this patch, excepting the ghost-block bounding box code, and it's fairly well tested by now.

**Comment by Codextroyer** [comment]
uhh hi! im a user of this mod for years then i got this update 1.14.2. i just want to ask how to use 2x3 solar panels without heating the wires?? thx :D :D

**Comment by AMIDIBOSS** [comment]
Use more wires

**Comment by Codextroyer** [comment]
so do you mean i add wires before or after the dc-dc converter ??? im sorry i just want to be careful haahahahaha

**Comment by AMIDIBOSS** [comment]
Connect your panel in series, and use higher voltage cable

**Comment by Codextroyer** [comment]
Yeah! thanks my friend :D :D

**Comment by Codextroyer** [comment]
why

**Comment by Codextroyer** [comment]
why did it stopped producing V's. its just 3:00 pm in game.
Help me pls, I want this style of panels :D :D :D

**Comment by cm0x4D** [comment]
Consider using the support channels, you might have faster and better support there: https://electrical-age.net/contact/

**Comment by AMIDIBOSS** [comment]
Did you ground the negative side of panels?

**Comment by Codextroyer** [comment]
yes i added ground cable before the series of panels, at the blue side

**Pull request merged**
