### PR TITLE
Added Spanish Translation

### PR DESCRIPTION
**Pull request by XxCoolGamesxX**
We translation in Spanish so the people can read it.

Thank to my team of Mega Planet (www.megaplanet.net).

### CODE REVIEW

**Comment by metc** [comment]
For now items name and description are only available in English. Thank you for your contribution.

**Comment by XxCoolGamesxX** [comment]
No problem. :D

**Comment by bloxgate** [comment]
Didn't part of the update to allow achievements to work with unlocalized names make the lang files start working again for some of the items, because I know the macerator did work when I tested it with the French lang file.

**Comment by metc** [comment]
@XxCoolGamesxX we made some progress with the translations. If you are interested, please create an account on Transiflex and help us to translate the mod in your language.
See https://www.transifex.com/electrical-age/eln/

**Comment by XxCoolGamesxX** [comment]
OK. My account name is some at in github. :P

**Comment by metc** [comment]
@XxCoolGamesxX you are in. Thanks for your help !

**Pull request merged**
