### PR TITLE
Semantic versioning as voted in #475

### PR DESCRIPTION
**Pull request by cm0x4D**
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/498)

### CODE REVIEW

**Comment by metc** [comment]
LGTM

**Comment by cm0x4D** [comment]
https://reviewable.io/reviews/Electrical-Age/ElectricalAge/498

**Comment by metc** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/498#-:-KNVYRoK1tBfgj_ylTjv:1417088721)_

**Comment by metc** [comment]
_[a discussion](https://reviewable.io:443/reviews/electrical-age/electricalage/498#-KNVYyIcJGnSK_XiaKL0:-KNVYyIcJGnSK_XiaKL1:-842840443) (no related file):_
Next thing to do is to update the `modinfo.json" file here: https://github.com/Electrical-Age/electrical-age.github.io/blob/develop/modinfo/modinfo.json

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/498)_

**Comment by cm0x4D** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/electrical-age/electricalage/498#-KNVYyIcJGnSK_XiaKL0:-KNW9fYl28cqGQpKHuuf:325870618) (no related file):_
<details><summary>

<i>Previously, metc (Christopher) wrote…</i></summary>



> Next thing to do is to update the `modinfo.json" file here: https://github.com/Electrical-Age/electrical-age.github.io/blob/develop/modinfo/modinfo.json
> </details>
> Ok. Can you do it? I am not sure what to write as date...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/498)_

**Pull request merged**
