### PR TITLE
Use a no-tool-required material for exporters. Fixes #628.

### LINKED ISSUE #628: [Bug] Converters instantly break with invalid tools
Attempting to use any tool which cannot pick up the converter will cause it to be destroyed instantly anyway, causing you to lose the object.

### PR DESCRIPTION
**Pull request by Baughn**
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/633)

### CODE REVIEW

**Comment by AMIDIBOSS** [comment]
Isn't that "the lazy way"?

**Comment by Baughn** [comment]
Maybe? I don't know. Constructing custom materials is disallowed by the permission set on that class, so I have to assume this is what you're meant to do.

**Comment by bloxgate** [comment]
No, you should be able to make new materials fairly easily.

Edit: Something like:
```java
public ComputerProbeBlock() {
		super(new Material(MapColor.stoneColor) {
			@Override
			public boolean isToolNotRequired() {
				return true;
			}
		});
	}
```

**Comment by Baughn** [comment]
By subclassing and overriding the methods that read its member variables, which will then disagree with the method return values, potentially causing conflicts with anything that happens to read the fields instead?

I mean, they're private, but...

That's still one of the ugliest pieces of code I've seen.

**Comment by bloxgate** [comment]
Good point, though it turns out the requiresNoTool variable defaults to true anyway, so just making a new material of whatever color you want would work too. It'd be nice to have a material class that can have those variables edited though. I wonder if there's already a library for that sort of thing.

**Pull request merged**
