### PR TITLE
Small bit of clarification to item constructors

### PR DESCRIPTION
**Pull request by Sukasa**
Since I want to contribute, I figured I would start small with little bits of clean-up and clarification in the code, and then as I learn the codebase more I would like to see if I can reduce the amount of code copy-paste around and help to keep the number of bugs down as well as make it easier to add to the codebase in future.

This simply adds an explicit enum for armour type (boots, legging, etc) to help clean away the 'magic numbers' in some of the code.  If you are open to it, I would definitely like to do more as stated above.

### CODE REVIEW

**Comment by Sukasa** [comment]
Actually on another note I'm wondering if there's an easier way to contact you directly; I have a few medium to large-size projects that I think would help clean and organize a lot of code and eliminate a large portion of the copy-pasting in Eln.java - however, I'd like to talk to you about it first and see if you would be open to such a set of changes before I start doing anything.

**Comment by Dolu1990** [comment]
Hi : D
Thanks for contribution !
Yes, i'm open to changes, copy past are bad :(
This mod was my first minecraft mod, it's a reason because some design are not very good. (It's the war between original game code and me XD)
Do you have skype ? my Id is **\* now transmited ****.

**Comment by nickdutto** [comment]
How big is the jump from 1.6.4 to 1.7.2 in terms of code changes?

**Comment by Sukasa** [comment]
item/block IDs are no longer mod-managed, for one.  It's all done internally/automatically.

**Comment by nickdutto** [comment]
That's bloody perfect, the pain involved in doing them... :+1:

**Comment by Dolu1990** [comment]
For this mod i have spend somthing like 30 hours of work XD
That was horrible, and some function become   func_51914 XD
All you old check like    blockToTest == null    (air)    must become     == Blocks.air.
Source of lots of bug XD
old network packet where removed, goodbye 250 packet with custom payload ^^

**Comment by nickdutto** [comment]
Damn, that's alot of work.

**Comment by Dolu1990** [comment]
Yes, depanding the mod that could be very hug,

**Pull request merged**
