### PR TITLE
[Feature Request] Radio tower

### PR DESCRIPTION
**Pull request by AMIDIBOSS**
Okay, here's the idea: Radio tower takes every signal in range of 128 blocks and extends it to 512 blocks. It sucks tons of power, propably powered by 800V. Maybe some gui to select channel? It's basicly a HUGE  signal repeater. Shall not be hard.
I aolso provide you with a model. I think @Baughn asked for it. Not sure. Anyway. It is BIG, not big. TALL, that's the right word.
BTW It's our first model 5 people worked on at the same time.  It took us like 5 min! Crazy isn't it? This way we can make like 15 models a day!
And if you don't like my idea, i won't cry if you use it for something else, i guess.
PS. Looks like the Bigger the model is, the more we enjoy making it!

---
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/615)

### CODE REVIEW

**Comment by cm0x4D** [comment]
Thanks. Just a hint, the rendering for big models is a little complicated, as during rendering it has the same light-level as the main block. So the bigger the models the more unrealistic they may end up when rendered.

**Comment by AMIDIBOSS** [comment]
So, what? Oh, you mean splitting model into smaller chunks, right?

**Comment by cm0x4D** [comment]
No. Not using more blocks as necessary.

**Comment by cm0x4D** [comment]
Just had a look at the model, it looks awesome.

**Comment by AMIDIBOSS** [comment]
Maybe the radio tower should be lit... What do you think?

**Pull request merged**
