### PR TITLE
Added MineTweaker support. fix #307

### LINKED ISSUE #307: Mod/MineTweaker support?
Good day.
May i ask about future support for Mod/MineTweaker?
I requesting it because it would be magnificent to tweak other mods through EA.
And maybe redo some recipes which already exist.
Thank you for reading.

### PR DESCRIPTION
**Pull request by marcin212**

### CODE REVIEW

**Comment by Niyudi** [comment]
It's not working for me. I don't know almost anything about coding, so I'm not sure if I understood how to use it right. I think I should write "mods.electricalage.Compressor[...]" for example, but in the chat Minetweaker says it didn't find the "electricalage" thingy.

**Comment by bloxgate** [comment]
This hasn't been merged yet.

**Comment by Niyudi** [comment]
Let's pretend that didn't happen... Well, I really want this implemented, hope it comes out soon :smile:

**Comment by grundyboy34** [comment]
This is a seriously needed feature, especially to increase compatibility in mod packs to solve some resource conflicts.

**Comment by Haggle1996** [comment]
FWIW, I haven't added EA to my pack, REVOLUTION|2, because it lacks Minetweaker support. It's a very critical feature for me to insure balance.

**Comment by Baughn** [comment]
Well, it doesn't look like @marcin212 will be back. Let me take a look...

**Pull request closed without merging**
