### PR TITLE
Client side audio looping

### PR DESCRIPTION
**Pull request by cm0x4D**
replaces #602

---
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/617)

### CODE REVIEW

**Comment by cm0x4D** [comment]
@Baughn can you have a look? I cherry picked and merged manually, hope I did not replace code...

**Comment by cm0x4D** [comment]
@Baughn I added a slew limiter for the generator audio and made it a little less loud, ok with that?

**Review by AMIDIBOSS — APPROVED** [review]

**Comment by Baughn** [comment]
I'm fine with that, of course. Usually am.

Maybe the slew limiter should be global, though? (I.e. applied in the looped-sound class, for all such sounds.)

**Comment by Baughn** [comment]
Give it a day or so before merging, though; I'm about to test this branch on Erisia.

**Comment by Baughn** [comment]
Or... less, I guess?

It works, and sounds awesome. I haven't tested absolutely everything, but I've tested most of these. The glitching is entirely gone.

**Comment by cm0x4D** [comment]
> Maybe the slew limiter should be global, though? (I.e. applied in the looped-sound class, for all such sounds.)

Oh yes, good idea. When you are happy and it did not crash anymore, you can merge it. I can add the global slew limit after the merge too.

The generator sample is not yes as smooth as I would like it to be. But for the moment this should do the trick...

**Pull request merged**
