### PR TITLE
A Better and Completely zh_CN.lang

### PR DESCRIPTION
**Pull request by KLszTsu**
https://github.com/KuangLei/Eln_zh_CN.lang_KLsz/
 I am the first Chinese to submit Eln, This is the page: http://www.mcbbs.net/thread-478326-1-1.html
 So I made a server with Eln, and also a Minecraft Live with Eln.
 Then, with help from the players in my server, and my audience in the Live, I've make this better and completely zh_CN.lang.
 I've talk to the translator before.
 Thanks

### CODE REVIEW

**Comment by KLszTsu** [comment]
Sorry but I am new to GitHub

**Comment by bloxgate** [comment]
Uh... you're pulling from 1.7.2-test into 1.7.10-mna. You need to hit this button button, make your changes there. Then PR from your fork into 1.7.10-mna.

**Comment by metc** [comment]
@KuangLei we made some progress with the translations. If you are interested, please create an account on Transiflex and help us to translate the mod in your language.
See https://www.transifex.com/electrical-age/eln/

**Comment by KLszTsu** [comment]
I’ve sent a request to https://www.transifex.com/electrical-age/eln/language/zh/ just now.

And, I’ve fully translated it.

The file with the email is the zh_cn.lang, just the translation of Eln_r50.

By the way, I reprint the article to the biggest minecraft forum in china, and it’s here, http://www.mcbbs.net/thread-478326-1-1.html.

Hope you can update faster#, I know java#.

Thanks

**Comment by metc** [comment]
@KuangLei thanks for keeping the forum post in Chinese up to date ;)
Your are in the ELN team on Transifex with @3TUSK. Thanks for your help !

**Pull request closed without merging**
