### PR TITLE
Added lang file for russian localization

### PR DESCRIPTION
**Pull request by ghost**
I don't know if there is need to add this file to some internal list containing all localizations. So i didn't touch anything else than .lang file.

P.S. I believe in you guys! Keep up the good work!

### CODE REVIEW

**Comment by metc** [comment]
Thanks for your contribution !

**Comment by AntonBoch1244** [comment]
@metc revert this PR this l10n not work because file _ru_RU.lang not ru_RU.lang and RU l10n is exist.

**Comment by metc** [comment]
Hi @AntonBoch1244 
We are working on the mod l10n. We will rename our translation file as required.
I will probably come back to you because the language file will have new entries soon.

**Comment by metc** [comment]
@dcbrwn we made some progress with the translations. If you are interested, please create an account on Transiflex and help us to translate the mod in your language.
See https://www.transifex.com/electrical-age/eln/

**Comment by ghost** [comment]
@metc ok, sure.

**Comment by metc** [comment]
@dcbrwn your are in the ELN Russian team on Transifex. Thanks for your help !

**Pull request merged**
