### PR TITLE
Make achievements rely on unlocalized names instead.

### PR DESCRIPTION
**Pull request by bloxgate**
This will stop them from breaking if a different language is used. Note: I'd think this is obvious but better safe than sorry: The basic research commit was just me adding some ideas to look into to the TODO statement, nothing to do with any sort of research system.
Changes made:
- Unlocalized names for some items/blocks. (Those using GenericItemBlockUsingDamage)
- Macerator achievement now uses unlocalized names
- Added macerator to US English language file
- Added myself to the contributors list in the readme :P 
- Revision number increased to 48

### CODE REVIEW

**Comment by bloxgate** [comment]
Anything I can do to help with testing this?

**Comment by Dolu1990** [comment]
Hi,
I'm sorry these times i'm under water because of relocation XD
maybe we could talk on skype about it ?

**Comment by bloxgate** [comment]
Sure, my skype name is bloxgate.

**Comment by bloxgate** [comment]
Just added a new commit. This works properly now. It appears I forgot to disable displaying the default display names. It breaks a lot of the stuff still using the language registry, although those that broke all have proper unlocalized names now so they can be put into the lang files.

**Comment by bloxgate** [comment]
@metc Is there any update on how the testing of this is going?

**Pull request merged**
