### PR TITLE
TO220 transistor model and texture 

### PR DESCRIPTION
**Pull request by AMIDIBOSS**
Not ready to merge.
transistors branch is like 70 commits behind and i don't know how to disable them and add Only the model.
And we still need heat textures, unless you use some tricky code thet will color existing textures red

---
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/614)

### CODE REVIEW

**Comment by Baughn** [comment]
The simplest way would be to open a pull request against the transistor branch instead of develop. That way it should only list your additions, presuming you haven't rebased anything.

**Comment by Baughn** [comment]
...I can't quite tell what you're rebasing against what, since I'm on mobile here.

If you poke me on IRC I can talk you through it, though.

**Comment by cm0x4D** [comment]
@AMIDIBOSS If you like I can just cherry-pick your change into my feature branch. Imho the simplest solution.

**Comment by AMIDIBOSS** [comment]
Alright. You can do that

**Comment by cm0x4D** [comment]
It is in the transistors branch, so I close this PR. Thanks!

**Pull request closed without merging**
