### PR TITLE
Create pt_BR.lang

### PR DESCRIPTION
**Pull request by ghost**
This is it...?
I mean, I wanna translate it all! Machines, descriptions...
It just seems so...
empty :disappointed:

### CODE REVIEW

**Comment by Radviger** [comment]
I have good news for you, I have modified the system of language in El Age and now he takes all strings and names from .lang file. Soon I will post it to mod developer.

**Comment by cm0x4D** [comment]
Thank you Radviger, that would probably help a lot of people actually using the mod. Maybe I find the time to do a german translation...

**Comment by ghost** [comment]
We :heart: Radviger

**Comment by Dolu1990** [comment]
Thanks  :)

**Pull request merged**
