### PR TITLE
The better and completely zh_CN.lang

### PR DESCRIPTION
**Pull request by KLszTsu**
https://github.com/KuangLei/Eln_zh_CN.lang_KLsz/
I am the first Chinese to submit Eln, This is the page: http://www.mcbbs.net/thread-478326-1-1.html
So I made a server with Eln, and also a Minecraft Live with Eln.
Then, with help from the players in my server, and my audience in the Live, I've make this better and completely zh_CN.lang.
I've talk to the translator before.
Thanks

### CODE REVIEW

**Comment by SaphireLattice** [comment]
Why did you nuked the README and model sources?

**Comment by KLszTsu** [comment]
?

**Comment by KLszTsu** [comment]
I seldom use GitHub.
I Click the "New Pull Requests" button, then "gh-pages "

**Comment by bloxgate** [comment]
Right so, gh-pages is the GitHub website for Eln, you need to make the pull request from whatever branch you commited to on your repository. Right now you have the gh-pages branch of Eln going into the 1.7.10-MNA branch of Eln, instead of the master branch of your fork going into the 1.7.10-MNA branch of Eln. Looking at your link you didn't actually create a fork which is the problem. Hit the Fork button in the top right, and make your changes in the resulting repository. Then pull request from your fork.

@Dolu1990 I think its safe to close this.

**Comment by cm0x4D** [comment]
@metc Can I delete the branch?

**Comment by metc** [comment]
@cm0x4D Äbä scho ;)

**Comment by metc** [comment]
Ouups sorry @cm0x4D , not sure that this was a good idea ;) The `gh-pages` branch had a redirection from the old website to the new one, could you restore it ?

**Comment by cm0x4D** [comment]
Nope, its gone. Any chance you have it still locally?

**Comment by metc** [comment]
Yes, I will find it, no problem

**Pull request closed without merging**
