### PR TITLE
Battery capacity is configurable in Eln.cfg balancing.

### PR DESCRIPTION
**Pull request by cm0x4D**
Battery capacity can be adjusted as factors for generation can be adjusted too.

Added minimal protection for overcharge when factor is reduced. Not a single battery exploded on the tutorial map, so it looks promising. More tests need though...

---

This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/428)

### CODE REVIEW

**Comment by Dolu1990** [comment]
https://www.google.ch/search?q=atomic+shrum&espv=2&biw=1633&bih=906&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiapYqJoqjMAhUsIcAKHVvdAvsQ_AUIBigB#tbm=isch&q=atomic+mushroom

**Comment by cm0x4D** [comment]
Hehe. Yes, did some tests increasing the factor, which the batteries liked a little less. Is there a problem when the (percental) charge becomes very small or is it the abrupt change of voltage/current?

**Comment by Dolu1990** [comment]
Ahhh yes, it could create a big current rush to capacitors/battery because of battery voltage change (as you said)
Maybe the mode should detect at launch nominalQ changes and then adapt the Q charge level of each batteryElement ?

**Comment by Baughn** [comment]
The better solution might be to store the charge as a fraction of battery capacity, if we want to support this scenario.

**Comment by Dolu1990** [comment]
Yes, it's right, it should not be to hard to change, i will do it.

**Comment by Domi1993** [comment]
is this feature inplemented now?

**Comment by cm0x4D** [comment]
Did you mean that @Dolu1990?

Just made a quick test, seems to work on the tutorial map (Factor: 1 -> 1000 -> 0.01).

As batteries can be slightly overloaded, I put the threshold to detect if the charge has to be converted to 1.1, but it was just a guess. How much can they get overloaded before they explode? We should better take that value...

One problem we could still have is when the factor is changed at the same time the map is opened the first time with the new version of the mod...

**Comment by Domi1993** [comment]
How i can get this build with gitbash on my PC?

**Comment by Domi1993** [comment]
I know how to get the 1.7.10MNA. Which command i must use for get it from the battery capacity factor branch

**Comment by cm0x4D** [comment]
@Domi1993 Well it is still quite experimental and if you go back to r50 you might experience this:

kf0a6vv

So make backups of the maps before doing anything else!

Do this in your cloned repository.

```
# git checkout feature/battery-capacity-factor
```

And then build as usual...

**Comment by Domi1993** [comment]
I make regulary backups of my maps, because i experimented with bigger capacitys too by modifing the eln.java and it happens that i forget to change it after clone the mod. And then my Powerplant says goodbye with a nice Boom :(

**Comment by cm0x4D** [comment]
@Domi1993 Could you test the change? Was it ok?

**Comment by Domi1993** [comment]
I dont had the time to test it but eventually tomorow i can test it. my Batterys have now 180KJ instead of 60KJ of energy stored, when they survive it then it's OK

**Comment by Domi1993** [comment]
when i enter "git  checkout feature/battery-capacity-factor" then build it makes the normal version there is no factor for battery capacity

**Comment by cm0x4D** [comment]
You need to start it at least once in order the config file gets updated.
...and it is in "balancing" section and not in "battery" section.

**Comment by Domi1993** [comment]
The batterys has exploded, with factor 1.0 they stored about 223KJ when i tested it.
we need to store the % value in the maps and not the KJ

**Comment by cm0x4D** [comment]
> we need to store the % value in the maps and not the KJ

Well that is exactly what this branch does. 

I still have to find the right value in order to detect if the value is in J or % when loading the block. Could you describe the problem a little more exact (how many batteries, actual charge, output power,...) or send me your map that causes the troubles?

**Comment by Domi1993** [comment]
There are 20 Life oriented batterys, on my map i got them 240KJ (i modified the eln.java then i builded it) there is s section thats for the batterys, i changed stdDischargeTime to stdDischargeTime \* 4. the same does the battery capacity factor now in the code
(stdDischargeTime \* batteryCapacityFactor).

I builded this branch, and then set in eln.config batterycapacityfactor to 1.0

Every of the 20 Batterys have power from -2W at night ... 7W at day
I think the current was not the problem, they blowed up just when i opened the map!

While The ELN Blocks are loading it happened

**Comment by cm0x4D** [comment]
It is very important that the map is opened at least once with the same factor as the values of the batteries have to be converted from J into % of maximal charge. So if you load your map for the first time with this branch, you need to set the factor to the same value as you had in the code (I think it would be 4). Otherwise the abrupt change of charge will produce current peaks that can destroy not only the batteries...

**Comment by Domi1993** [comment]
I'll try it when i have time. That means the mod will read first time the J of my Batterys and store it as %. When i do the factor to 8 my batterys are charged at 100% right? But is that not a little cheaty when i can set a low factor to charge it and then put it to i.e. 20.0 and use energy i don't produced? 

I test out this what happens and tell it here

**Comment by cm0x4D** [comment]
> But is that not a little cheaty when i can set a low factor to charge it and then put it to i.e. 20.0 and use energy i don't produced?

Yes that's in fact the case. But if we change the battery charge (%) at startup to much, they will explode like yours did, so we do not really have an option here.

**Comment by Baughn** [comment]
Someone who can change the server configuration could also, for example, set themselves to creative and spawn in a voltage source. I can think of no serious reason to worry about cheating here.

**Comment by Domi1993** [comment]
Yes but i just think when someone did this in single player

**Comment by cm0x4D** [comment]
It is open source, we can not avoid cheating anyway, as anyone can change that factor in Eln.java already like you actually did. Basically as soon as you touch Eln.cfg you are actually already some kind of cheating...

**Comment by Baughn** [comment]
If you're in single player, you can always set yourself to creative. And if you're playing Eln with some kind of modpack, then there will always be other mods that are more powerful or at least easier to use, so...

I think we need to trust the players to not ruin their own fun. :)

**Comment by Domi1993** [comment]
It's working now my Batterys have survived with 240KJ to 30KJ.
it's now the percent thats stored in the map

**Comment by cm0x4D** [comment]
Good to hear. I guess some more tests are still needed...

**Comment by Domi1993** [comment]
I think we need a lower limit for the Batterycapacityfactor.

I can test out which factor will be dangerous (low capacity) if you want

**Comment by cm0x4D** [comment]
Ok. Some tests would be nice, but imho if someone puts in there ridiculous values he will get what he deserves...

**Comment by Domi1993** [comment]
Is this feature avialable in the new release?

**Comment by metc** [comment]
@Domi1993 No, these changes are not yet merge in the develop branch.

FYI, all changes, fixes and improvement of the r51 release are described here: https://electrical-age.net/news/release-1-11/

**Comment by metc** [comment]
Related to #393

**Comment by cm0x4D** [comment]
I need to ensure that the batteries are not empty when converting to per-unit. The decision is actually made using the Q value: If it is smaller than 1.1 we assume that Q is saved as per-unit, all values bigger than 1.1 will be converted to per-unit. This can lead to problems for very empty batteries - They will instantly go from almost 0% to 110% of charge. This does not end well!

I have to do some additional check in order to avoid the case above - This should be quite simple by checking the actual voltage of the battery according to the nominal voltage.

After that the feature can be merge and be part of the next release...

**Comment by cm0x4D** [comment]
Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/428)_

**Pull request merged**
