### PR TITLE
Grammar and wording fixes - Part 2

### PR DESCRIPTION
**Pull request by DrummingFish**

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks : D

**Comment by DrummingFish** [comment]
Just as before, no problem :). Still a lot more to go through though haha. Oh and do you mind if I do some general cleanup and formatting?

**Comment by Dolu1990** [comment]
There is no probleme ^^
When you say formating, it's item dialog formating ? for that to, not probleme  :)

**Comment by DrummingFish** [comment]
I just mean general layout of code but yeah dialog too. There might not be any need for any code reformatting but I just thought I'd check with you first :).

**Comment by Dolu1990** [comment]
Hmmm, Code formating is for me not very important. Don't wast your time on that, exept if it's a plesure for you, Juste, don't reformate eln.java, it's a to mutch often modified file with very special formating.
For item dialog formating => it's welcome  ^^

**Comment by DrummingFish** [comment]
Haha yeah I understand. It kinda is a pleasure thing actually so I might throw some reformatting in at times. I promise I won't touch eln.java :D

**Pull request merged**
