### PR TITLE
Assets #351

### PR DESCRIPTION
**Pull request by metc**
This PR is related to the issue https://github.com/Dolu1990/ElectricalAge/issues/351.

I created a resource white-list to include only necessary asset files in the release Jar, and I also detected some unused files.
I also added a `META-INF` file to the release Jar.

I tested this locally on the tuto map and I thinks every textures, model, sounds are OK. Many files have been removed from the release jar (r50 file was 6.3Mo, r51 is 5.7Mo).

@cm0x4D @lambdaShade @Dolu1990 please review. I will merge this if it is ok for you.

**From now, please use lowercase file extensions for asset files, or the files will not be filtered !**

### CODE REVIEW

**Comment by lambdaShade** [comment]
Excellent. Size reduced as planned (https://github.com/Dolu1990/ElectricalAge/commit/ebba4148742103b272ba5b3aa35b46e32e419e3e). ^^

**Comment by metc** [comment]
Ping @cm0x4D @lambdaShade @Dolu1990. Please review.

**Comment by cm0x4D** [comment]
For me its ok.

**Comment by lambdaShade** [comment]
ACK.

**Comment by metc** [comment]
LGTM. I will merge this soon.
@cm0x4D Can you check if this PR is compatible with your commit https://github.com/Electrical-Age/ElectricalAge/commit/3bae22708f546053a51174b4edc99d995fad4695 ?

**Pull request merged**
