### PR TITLE
Clean up - Part 1

### PR DESCRIPTION
**Pull request by DrummingFish**
As this is my first pull request for clean up, can you confirm whether you like these changes?

If you don't like them then just let me know and don't pull :) I won't be offended.

Also, would you like me to remove all the auto-generated stubs?

### CODE REVIEW

**Comment by Dolu1990** [comment]
All these change are good and make code better ^^
As you can se, my coding formating has change at the middle of project XD
Thanks you :)

**Comment by DrummingFish** [comment]
No problem :). I'll carry on with cleaning up then :D

Oh and do you mind if I do pull requests with multiple commits? It means that whatever size the commit is you'll be able to see the changes. With my huge commit yesterday you couldn't view the changes because too much had been altered in one commit.

**Comment by DrummingFish** [comment]
Oh and again, would you like me to remove all the auto-generated stubs?

**Comment by Dolu1990** [comment]
Ahhh yes, true, i have forget to answer to auto generated stubs.  
yes you can ^^

**Comment by DrummingFish** [comment]
Great thanks :)

**Pull request merged**
