### PR TITLE
Client side audio looping

### PR DESCRIPTION
**Pull request by cm0x4D**
Move audio looping to client side using the new API:

- [x] Turbines
- [x] DC/DC Converter (Transformer)
- [x] All machines
- [x] Autominer
- [x] Fuel Generator
- [x] ~~Lamp Socket~~ (Was just old code needed to be removed)
- [x] Firedetector
- [x] ~~Grid transformer~~ (Not used yet)
- [x] Eletricalpole

---
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/602)

### CODE REVIEW

**Comment by AMIDIBOSS** [comment]
Lamp socket? I guess, ergonomic light bulbs, but... They only Click on startup. That has to be looped? And electrical pole? Does it make any sound at all?

**Review by AMIDIBOSS — APPROVED** [review]

**Comment by cm0x4D** [comment]
Theoretically it is done for the electrical pole, I could not test it yet, as it always did explode before I had the chance to hear something...

**Comment by Baughn** [comment]
The electrical pole is actually pretty tough to make explode...

Tie one pole to an electrical source at 3180V, another to a source at 3200V. This should put it at about 85% load.

**Comment by AMIDIBOSS** [comment]
Is there any diffrence between putting 3180 - 3200
And 0 - 20?

**Comment by AMIDIBOSS** [comment]
And what sound will grid transformer output?

**Comment by cm0x4D** [comment]
> And what sound will grid transformer output?

Humming when overloaded like the regular one.

**Comment by cm0x4D** [comment]
> Tie one pole to an electrical source at 3180V, another to a source at 3200V. This should put it at about 85% load.

Thanks @Baughn, that did the trick. What I did not understood is that the load factor actually was 3.3 with a deltaU=20V, so rather 330% rather than 85%.

**Comment by cm0x4D** [comment]
Tried to rebase, it is a complete mess, so #617 replaces this PR.

**Pull request closed without merging**
