### PR TITLE
Update fr_FR.lang

### PR DESCRIPTION
**Pull request by Mazdallier**

### CODE REVIEW

**Comment by metc** [comment]
Are you sure that french accent and all special characters are displayed correctly, for instance in the mod info page ?

**Comment by Mazdallier** [comment]
French accent are included in the UTF-8 format in minecraft version 1.7.10. 
Would you want a testing in a MultiMC instance ?

**Comment by metc** [comment]
Salut @Mazdallier, we made some progress with the translations. If you are interested, please create an account on Transiflex and help us to translate the mod in your language.
See https://www.transifex.com/electrical-age/eln/

**Comment by Mazdallier** [comment]
You have metc to do that.

**Comment by Mazdallier** [comment]
Je veux bien aider s'il le faut...

**Comment by metc** [comment]
Salut @Mazdallier, tu es dans la team ELN fr sur Transifex. Merci d'avance pour ton aide ;)

**Pull request merged**
