### PR TITLE
Added issue-requested lamps

### PR DESCRIPTION
**Pull request by AMIDIBOSS**
- Modern Street Light,
 - Spotlight
 - Floor lamp
Only models, no code

---
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/552)

### CODE REVIEW

**Comment by bloxgate** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[Spotlight/Spotlight.png, line 0 at r1](https://reviewable.io:443/reviews/electrical-age/electricalage/552#-KZ2t7DH_Fp_gxIiM1L5:-KZ2t7DH_Fp_gxIiM1L6:b-vedgtp) ([raw file](https://github.com/electrical-age/electricalage/blob/b45bb7189d4447ec896ffad2b0b7677e8b5fc8a4/Spotlight/Spotlight.png#L0)):*
Did you mean to include this one? It looks more like a sample picture from when you were creating the lamp in blender.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/552)*

**Comment by bloxgate** [comment]
I think the models should be in the actual models folder.

---

Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/552#-:-KZ2uAHZrXGq6-A-jysp:boww7kv)*

**Comment by AMIDIBOSS** [comment]
> Spotlight/Spotlight.png, line 0 at r1 (raw file):
Did you mean to include this one? It looks more like a sample picture from when you were creating the lamp in blender.

That was an accident, I didn't saw that file. We don't need this, I'll remove it.

**Comment by AMIDIBOSS** [comment]
Done, removed Unwanted file.
So my models are accepted and will be pulled into the mod?

**Comment by bloxgate** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[Spotlight/Spotlight.png, line  at r1](https://reviewable.io:443/reviews/electrical-age/electricalage/552#-KZ2t7DH_Fp_gxIiM1L5:-KZ352Kfi1FAHD5IX2hz:bb6ywmx) ([raw file](https://github.com/electrical-age/electricalage/blob/b45bb7189d4447ec896ffad2b0b7677e8b5fc8a4/Spotlight/Spotlight.png#L)):*
<details><summary><i>Previously, bloxgate (Gregory Maddra) wrote…</i></summary><blockquote>

Did you mean to include this one? It looks more like a sample picture from when you were creating the lamp in blender.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/552)*

**Comment by cm0x4D** [comment]
Move the files to *src/main/resources/assets/eln/model-to-be-integrated*. Then it's fine.

**Comment by AMIDIBOSS** [comment]
Done

**Comment by cm0x4D** [comment]
You need to push the changes to your feature branch.

**Comment by AMIDIBOSS** [comment]
Done
Sorry for the wait, i needed time to figure out what were you meaning.(I could ask, I know)
I didn't saw that i moved files in develop branch, not feature. Sorry again.
I also added nicer downlink model (The old one is ugly to me, the new one matches new transformer model)
Guess You can merge now. If theres something else I need to do, tell me!

**Comment by cm0x4D** [comment]
Reviewed 1 of 1 files at r2, 30 of 33 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/electrical-age/electricalage/552)*

**Comment by cm0x4D** [comment]
Merged. Thanks!

**Pull request merged**
