### PR TITLE
PID chip GUI slider step is 1.0.

### PR DESCRIPTION
**Pull request by cm0x4D**
This change is [Reviewable](https://reviewable.io/reviews/electrical-age/electricalage/620)

### CODE REVIEW

**Comment by Baughn** [comment]
I wonder if it could be made logarithmic?

**Comment by cm0x4D** [comment]
Good idea, would actually make sense for the PID parameters. I do not see a technical problem, but first I would really like to integrate the fridge (it is about time...).

**Comment by Baughn** [comment]
Fridge, of all things...

What does it *do*?

**Comment by cm0x4D** [comment]
Ups, was still logged as the bot...

**Comment by AMIDIBOSS** [comment]
Bot came to life😱

**Pull request merged**
