### PR TITLE
Fixes #279

### LINKED ISSUE #279: [Feature-Request] Wireless TX Range config
Increasing/decreasing the wireless range for transceivers and receivers would be great.

### PR DESCRIPTION
**Pull request by cm0x4D**
Allows to configure the wireless TX range in Eln.cfg

### CODE REVIEW

**Comment by cm0x4D** [comment]
@Electrical-Age/devs: Any opposition against this feature? Can I merge?

**Comment by Baughn** [comment]
In case it becomes relevant: I'm planning to add a powered-antenna multiblock at some stage. I'm not opposed to this one, especially as I have no idea when that might happen.

**Comment by metc** [comment]
I did not play with this feature, but short question: what is appending if the TX range is a negative value ? Should you not check the bounds of the user input ?

**Comment by cm0x4D** [comment]
I guess a negative value would be something like the flight mode on your mobile ;-)

**Comment by cm0x4D** [comment]
If someone puts stupid values in the configuration, he should imho get what he deserves...

**Comment by metc** [comment]
LGTM, you can merge.

General remark: each descriptors should maybe have up/down limits for each values so we could check the bounds automatically and print warning messages when required.

**Comment by cm0x4D** [comment]
Agree, would be good for all settings. I will create an issue for that...

**Comment by Baughn** [comment]
Forge's configuration API already comes with support for range limits. You should use that, if possible...

**Pull request merged**
